# Generated by Django 5.0.6 on 2024-06-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='userProfiles'),
        ),
    ]
